config/routes.rb
Rails.application.routes.draw do
  resources :surveys
  get "/result" => 'surveys#result'

  root 'surveys#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
  end

  def new

  end

  def create
    session[:user] = params
    
    flash[:name] = params[:name]
    flash[:location] = params[:location]
    flash[:language] =params[:language]
    flash[:comments] =params[:comments]

    if session[:count]
      session[:count]+=1
    else
      session[:count]=1
    end
    flash[:count] = session[:count]
     redirect_to('/result')
  end


  def result
    @user = session[:user]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyForm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/surveys/destroy.html.erb
<h1>Surveys#destroy</h1>
<p>Find me in app/views/surveys/destroy.html.erb</p>

app/views/surveys/edit.html.erb
<h1>Surveys#edit</h1>
<p>Find me in app/views/surveys/edit.html.erb</p>

app/views/surveys/index.html.erb
<h1>Surveys#index</h1>
<p>Find me in app/views/surveys/index.html.erb</p>

app/views/surveys/new.html.erb
<h1>Surveys#new</h1>
<p>Find me in app/views/surveys/new.html.erb</p>


<form action='/surveys' method='post'>
  <%= tag(:input,:type =>"hidden",:name => request_forgery_protection_token.to_s,:value => form_authenticity_token)%>

  <h3>Your Name:</h3>
  <input type='text' name='name'>

  <h3>Dojo Location:</h3>
  <select name='location'>
    <option value='Mountain View'>Mountain View</option>
    <option value='Dallas'>Dallas</option>
    <option value='Chicago'>Chicago</option>
    <option value='Burbank'>Burbank</option>

  </select>

  <h3>Favorite Language:</h3>
  <select name='language'>
    <option value='Javascript'>Javascript</option>
    <option value='iOs'>iOs</option>
    <option value='Python'>Python</option>
    <option value='Css'>Css</option>
    <option value='Node.js'>Node.js</option>
  </select><br>

  <h3>Comments?</h3>
  <textarea rows='3' cols='40' name='comments'></textarea>
  <input type='submit'>
</form>

app/views/surveys/result.html.erb
<h1>Surveys#result</h1>
<p>Find me in app/views/surveys/result.html.erb</p>


<h2>Results</h2>
  <% if flash[:count]%>
  <div>
    <p>Thanks for submitting this form! You have submitted this form <%= flash[:count] %> times now.</p>
  </div>
  <% end %>
<div>
 

  User Name: <%= @user['name'] %><br>
  User Location: <%= @user['location'] %><br>
  User Language: <%= @user['language'] %><br>
  User Comments: <%= @user['comments'] %><br><br>

  <!-- <a href="<%=new_survey_path%>">Go Back</a> -->
  <a href="/surveys/new"><input type='submit' value='Go Back'></a>
</div>

app/views/surveys/show.html.erb
<h1>Surveys#show</h1>
<p>Find me in app/views/surveys/show.html.erb</p>

app/views/surveys/update.html.erb
<h1>Surveys#update</h1>
<p>Find me in app/views/surveys/update.html.erb</p>